export const API_KEY = 'c285797738b3abb8c244d8be0159116c';
export const GET_WEATHER_REQUEST = 'GET_WEATHER_REQUEST';
export const GET_WEATHER_SUCCESS = 'GET_WEATHER_SUCCESS';
export const ON_SEARCH = 'ON_SEARCH';
export const ADD_ITEM = 'ADD_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const NOT_SELECTED = 'NOT_SELECTED';
export const FORECAST_SUCCESS = 'FORECAST_SUCCESS';
